//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMediaModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public Channel()
        {
            this.Subscriptions = new HashSet<Subscription>();
            this.Videos = new HashSet<Video>();
        }
    
        public int Id { get; set; }
        public int ProfileId { get; set; }
        public string Name { get; set; }
        public int SubscriptionCount { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
