//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMediaModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.LookUps = new HashSet<LookUp>();
            this.Profiles = new HashSet<Profile>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string EmailConfigrationToken { get; set; }
        public string EmailCnfigrationTokenExpiry { get; set; }
        public string PasswordResetToken { get; set; }
        public string PasswordResetTokenExpiry { get; set; }
        public byte[] IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<LookUp> LookUps { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
    }
}
