//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMediaModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.LookUps = new HashSet<LookUp>();
        }
    
        public int Id { get; set; }
        public string Role1 { get; set; }
    
        public virtual ICollection<LookUp> LookUps { get; set; }
    }
}
