//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMediaModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public int ChannelId { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public Nullable<int> Likes { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
